pipeline {
    agent {
        label 'Agent-1'
    }

    environment {
        EC2_IP = 'backend.mydevops.tech' // Replace with your EC2 instance's public/private IP
    }

    stages {
        stage('Connect and Configure EC2') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'ssh-auth', usernameVariable: 'EC2_USER', passwordVariable: 'EC2_PASS')]) {
                    script {
                        sh '''
                            sshpass -p "$EC2_PASS" scp -o StrictHostKeyChecking=no /home/ec2-user/jenkins/backend.service "$EC2_USER@$EC2_IP:/tmp/backend.service" << EOF
                            EOF
                            '''
                        sh'''
                            sshpass -p "$EC2_PASS" ssh -o StrictHostKeyChecking=no "$EC2_USER@$EC2_IP" << EOF
                            echo "Connection Successful to EC2 Instance!"
                            sudo dnf module disable nodejs -y
                            curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
                            sudo yum install -y nodejs
                            sudo dnf install nodejs -y
                            sudo rm -rf /app
                            sudo rm -rf /tmp/*
                            sudo mkdir -p /app
                            sudo mkdir -p /tmp
                            sudo curl -o /tmp/backend.zip https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
                            sudo cd /app
                            sudo rm -rf /app/*
                            sudo unzip -o /tmp/backend.zip
                            sudo cd /app
                            sudo npm install                          
                            sudo mv /tmp/backend.service /etc/systemd/system/backend.service
                            sudo systemctl daemon-reload
                            sudo systemctl start backend
                            sudo systemctl enable backend
                        EOF
                        '''
                    }
                }
            }
        }
    }
}
