pipeline {
    agent{
        label 'Agent-1'
    }

    environment {
        EC2_IP = 'backend.mydevops.tech' // Replace with your EC2 instance's public/private IP
    }

    stages {
        stage('Connect to EC2') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'ssh-auth', usernameVariable: 'EC2_USER', passwordVariable: 'EC2_PASS')]) {
                    script {
                        sh '''
                        sshpass -p "$EC2_PASS" ssh -o StrictHostKeyChecking=no "$EC2_USER@$EC2_IP" 
                        echo "Connection Successful to EC2 Instance!"
                        sudo dnf module disable nodejs -y
                        curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
                        sudo yum install -y nodejs
                        sudo dnf install nodejs -y
                        sudo mkdir -p /app
                        sudo curl -o /tmp/backend.zip https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
                        sudo cd /app
                        sudo unzip /tmp/backend.zip
                        sudo cd /app
                        sudo npm install
                        sudo cp /d/devops/mylearning/CICD/backend/backend.service /etc/systemd/system/backend.service
                        sudo systemctl daemon-reload
                        sudo systemctl start backend
                        sudo systemctl enable backend
                        '''
                    }
                }
            }
        }
    }
}