pipeline{
    agent{
        label 'Agent-1'
    }
    environment {
        mysql_host = 'mysql.mydevops.tech' // Replace with your EC2 public DNS or IP
        PRIVATE_KEY = credentials('mysql-key')
    }
    stages{
        stage('login into mysql ec2'){
            steps{
                script{
                    writeFile file: 'ec2-key.pem', text: PRIVATE_KEY
                    sudo sh 'chmod 600 ec2-key.pem'
                    sh """
                        ssh -i ec2-key.pem -o StrictHostKeyChecking=no ec2-user@$mysql_host <<EOF
                        echo "Successfully logged in to mysql_host"
                    """
                }
            }
        }
    }
}